Update cuml version to 24.02 in ci/Dockerfile
To fix: https://github.com/NVIDIA/spark-rapids-ml/issues/533

```
PackagesNotFoundError: - cuml=23.12* in the channel rapidsai-nightly
```

On branch-24.02, Build Docker image failed as below due to referring to ARG CUML_VER=23.12, with file : ci/Dockerfile

Only 24.02 cuml packages available in the rapids-nightly conda channel : https://anaconda.org/rapidsai-nightly/cuml/files

Change ARG CUML_VER=23.12 to ARG CUML_VER=24.02 to PASS the docker build

Signed-off-by: Tim Liu <timl@nvidia.com>