Avoid hitting BufferHolder limit when kmeans model is larger than int_max (#1009)
error message when kmeans model > 2G:

java.lang.IllegalArgumentException: Cannot grow BufferHolder by size
33288 because the size after growing exceeds size limitation 2147483632

---------

Signed-off-by: Jinfeng <jinfengl@nvidia.com>